[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#00E5FF"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1A1D24"
textColor = "#FFFFFF"
font = "sans serif"
